# Introduction to Numpy

In [1]:
import numpy as np

1. Creating an array

In [2]:
arr = np.array([1,2,34,5,6,7])

In [3]:
print(arr.ndim)

1


In [4]:
arr0 = np.array(89)
print(arr0.ndim)

0


In [7]:
arr2 = np.array([[1,2,3,4], [6,7,8,9]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [6 7 8 9]]
2


In [8]:
arr3 = np.array([1,2,3,4,5,6,7,8,9], ndmin=5)
print(arr3)
print(arr3.ndim)

[[[[[1 2 3 4 5 6 7 8 9]]]]]
5


2. Accessing the elements of the array

In [14]:
print(arr3[0][0][0][0][3])

4


In [15]:
print(arr2)

[[1 2 3 4]
 [6 7 8 9]]


In [16]:
print(arr2[1][2])

8


3. Slicing in array Elements

In [17]:
print(arr2[1][1:])

[7 8 9]


4. Converting data types

In [18]:
print(arr3.dtype)

int64


In [19]:
arr4 = np.array(arr2, dtype='S')
print(arr4)

[[b'1' b'2' b'3' b'4']
 [b'6' b'7' b'8' b'9']]


In [20]:
arr5 = arr2.astype(float)
print(arr5)

[[1. 2. 3. 4.]
 [6. 7. 8. 9.]]


In [21]:
arr6 = arr5.copy()
print(arr6)

[[1. 2. 3. 4.]
 [6. 7. 8. 9.]]


In [22]:
arr7 = arr5.view()


In [24]:
print("Array arr6: ", arr6)
print('Size of arr6: ',arr6.size)
print('Shape of arr6: ',arr6.shape)
print('Length of arr6: ', len(arr6))
print('Dimension of arr6: ', arr6.ndim)

Array arr6:  [[1. 2. 3. 4.]
 [6. 7. 8. 9.]]
Size of arr6:  8
Shape of arr6:  (2, 4)
Length of arr6:  2
Dimension of arr6:  2


In [25]:
arr8 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr9 = arr8.reshape(3,4)
print(arr9)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8])
arr11 = np.concatenate((arr1,arr2))
print(arr11)

[1 2 3 4 5 5 6 7 8]


In [31]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])
arr11 = np.stack((arr1,arr2))
print(arr11)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [32]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array_split(arr1,2)
print(arr2)

[array([1, 2, 3]), array([4, 5])]


In [33]:
np.searchsorted(arr1, 4)

np.int64(3)

In [ ]:
# get the values in even index position
np.where(arr1%2==0)

(array([1, 3]),)

In [ ]:
arr16 = arr1[arr1%2==0] # values which are even
print(arr16)

[2 4]
